import type { InterfaceLanguage } from '@/lib/interfaceLanguage';

export const SESSIONS_COPY = {
  uk: {
    auth: { admin: 'Admin', account: 'Акаунт', signOut: 'Вийти', menu: 'Меню', language: 'Мова інтерфейсу' },
    gate: {
      blockedTitle: 'Доступ призупинено',
      waitingTitle: 'Ви у списку очікування',
      blockedBody: 'Доступ до Бюро для цього акаунта наразі закрито. Якщо вважаєте це помилкою — напишіть нам.',
      waitingBody: 'Дякуємо за реєстрацію! Ми відкриваємо доступ поступово, невеликими групами. Щойно настане ваша черга — ви зможете розпочати розслідування з цього екрана.',
    },
    stats: { active: 'Активних', paused: 'На паузі', completed: 'Завершено', messages: 'Повідомлень' },
    sections: { open: 'Відкриті справи', closed: 'Закриті справи', available: 'Доступні справи' },
    empty: {
      title: 'Жодних відкритих справ',
      body: 'Архів порожній. Оберіть справу нижче, щоб розпочати розслідування.',
    },
    card: {
      played: 'Вечір зіграно',
      closed: 'Закрито',
      paused: 'На паузі',
      campaign: 'Кампанія',
      active: 'Активна',
      delete: 'Видалити',
      confirmDelete: 'Видалити справу?',
      yes: 'Так',
      cancel: 'Скасувати',
      review: 'Переглянути',
      continue: 'Продовжити',
      caseFile: 'Справа',
      oneShot: 'one-shot',
      campaignBadge: 'кампанія',
      start: 'Розпочати розслідування',
      sessionFallback: (n: number) => `${n}-та сесія`,
      sessionLabels: ["перша", "друга", "третя", "четверта", "п'ята", "шоста", "сьома", "восьма", "дев'ята", "десята"],
    },
    difficulty: { beginner: 'Початківець', intermediate: 'Середній', advanced: 'Складний' },
    modal: {
      caseLabel: 'Справа',
      close: 'Закрити',
      back: 'Назад',
      classFor: 'Клас для',
      player: 'Гравця',
      caseName: 'Назва справи',
      casePlaceholder: 'Напр: Ніч у Бостоні',
      players: 'Гравці (1–4)',
      playerName: (n: number) => `Ім'я гравця ${n}`,
      removePlayer: 'Видалити гравця',
      change: 'змінити',
      chooseClass: 'Обрати клас',
      addPlayer: 'Додати гравця',
      opening: 'Відкриваємо справу...',
      open: 'Відкрити справу',
      submitHint: 'Щоб відкрити справу, заповніть:',
      missingName: 'назву справи',
      missingPlayer: "ім'я гравця",
      missingClass: 'клас гравця',
    },
  },
  en: {
    auth: { admin: 'Admin', account: 'Account', signOut: 'Sign out', menu: 'Menu', language: 'Interface language' },
    gate: {
      blockedTitle: 'Access paused',
      waitingTitle: 'You are on the waitlist',
      blockedBody: 'Bureau access for this account is currently closed. If this looks wrong, please contact us.',
      waitingBody: 'Thanks for registering. We are opening access gradually in small groups. When your turn arrives, you will be able to start an investigation from this screen.',
    },
    stats: { active: 'Active', paused: 'Paused', completed: 'Completed', messages: 'Messages' },
    sections: { open: 'Open cases', closed: 'Closed cases', available: 'Available cases' },
    empty: {
      title: 'No open cases',
      body: 'The archive is empty. Choose a case below to begin an investigation.',
    },
    card: {
      played: 'Evening played',
      closed: 'Closed',
      paused: 'Paused',
      campaign: 'Campaign',
      active: 'Active',
      delete: 'Delete',
      confirmDelete: 'Delete case?',
      yes: 'Yes',
      cancel: 'Cancel',
      review: 'Review',
      continue: 'Continue',
      caseFile: 'Case',
      oneShot: 'one-shot',
      campaignBadge: 'campaign',
      start: 'Start investigation',
      sessionFallback: (n: number) => `session ${n}`,
      sessionLabels: ['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth'],
    },
    difficulty: { beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced' },
    modal: {
      caseLabel: 'Case',
      close: 'Close',
      back: 'Back',
      classFor: 'Class for',
      player: 'Player',
      caseName: 'Case name',
      casePlaceholder: 'E.g. A Night in Boston',
      players: 'Players (1-4)',
      playerName: (n: number) => `Player ${n} name`,
      removePlayer: 'Remove player',
      change: 'change',
      chooseClass: 'Choose class',
      addPlayer: 'Add player',
      opening: 'Opening case...',
      open: 'Open case',
      submitHint: 'To open a case, complete:',
      missingName: 'case name',
      missingPlayer: 'player name',
      missingClass: 'player class',
    },
  },
  es: {
    auth: { admin: 'Admin', account: 'Cuenta', signOut: 'Salir', menu: 'Menu', language: 'Idioma de interfaz' },
    gate: {
      blockedTitle: 'Acceso pausado',
      waitingTitle: 'Estas en la lista de espera',
      blockedBody: 'El acceso al Bureau para esta cuenta esta cerrado por ahora. Si parece un error, escribenos.',
      waitingBody: 'Gracias por registrarte. Estamos abriendo acceso poco a poco, en grupos pequenos. Cuando llegue tu turno, podras iniciar una investigacion desde esta pantalla.',
    },
    stats: { active: 'Activas', paused: 'En pausa', completed: 'Completadas', messages: 'Mensajes' },
    sections: { open: 'Casos abiertos', closed: 'Casos cerrados', available: 'Casos disponibles' },
    empty: {
      title: 'No hay casos abiertos',
      body: 'El archivo esta vacio. Elige un caso abajo para empezar una investigacion.',
    },
    card: {
      played: 'Noche jugada',
      closed: 'Cerrado',
      paused: 'En pausa',
      campaign: 'Campana',
      active: 'Activa',
      delete: 'Eliminar',
      confirmDelete: 'Eliminar caso?',
      yes: 'Si',
      cancel: 'Cancelar',
      review: 'Revisar',
      continue: 'Continuar',
      caseFile: 'Caso',
      oneShot: 'one-shot',
      campaignBadge: 'campana',
      start: 'Iniciar investigacion',
      sessionFallback: (n: number) => `sesion ${n}`,
      sessionLabels: ['primera', 'segunda', 'tercera', 'cuarta', 'quinta', 'sexta', 'septima', 'octava', 'novena', 'decima'],
    },
    difficulty: { beginner: 'Principiante', intermediate: 'Intermedia', advanced: 'Avanzada' },
    modal: {
      caseLabel: 'Caso',
      close: 'Cerrar',
      back: 'Atras',
      classFor: 'Clase para',
      player: 'Jugador',
      caseName: 'Nombre del caso',
      casePlaceholder: 'Ej.: Una noche en Boston',
      players: 'Jugadores (1-4)',
      playerName: (n: number) => `Nombre del jugador ${n}`,
      removePlayer: 'Eliminar jugador',
      change: 'cambiar',
      chooseClass: 'Elegir clase',
      addPlayer: 'Anadir jugador',
      opening: 'Abriendo caso...',
      open: 'Abrir caso',
      submitHint: 'Para abrir un caso, completa:',
      missingName: 'nombre del caso',
      missingPlayer: 'nombre del jugador',
      missingClass: 'clase del jugador',
    },
  },
} satisfies Record<InterfaceLanguage, Record<string, unknown>>;

export const ACCOUNT_COPY = {
  uk: {
    back: 'Сесії',
    title: 'Дані та приватність',
    languageTitle: 'Мова інтерфейсу',
    languageBody: 'Змінює мову навігації, акаунта і списку справ для цього акаунта.',
    saved: 'Збережено',
    saving: 'Зберігаємо...',
    failed: 'Не вдалося зберегти мову.',
    exportTitle: 'Завантажити мої дані',
    exportBody: 'Вивантажити всі дані, повʼязані з акаунтом (профіль, сесії, повідомлення, кампанії, відгуки) одним файлом JSON.',
    exportButton: 'Завантажити JSON',
    deleteTitle: 'Видалити акаунт',
    deleteBody: 'Назавжди видаляє ваш акаунт і всі повʼязані дані (сесії, повідомлення, кампанії). Дію не можна скасувати.',
    deleteButton: 'Видалити акаунт',
    confirmTitle: 'Підтвердіть видалення',
    confirmBody: 'Це назавжди видалить акаунт',
    confirmBodyAfter: 'і всі дані. Введіть пароль, щоб підтвердити.',
    password: 'Пароль',
    cancel: 'Скасувати',
    deleting: 'Видалення...',
    deleteForever: 'Видалити назавжди',
    passwordRequired: 'Введіть пароль для підтвердження.',
    wrongPassword: 'Невірний пароль.',
    deleteFailed: 'Не вдалося видалити акаунт.',
    networkError: 'Помилка зʼєднання. Спробуйте ще раз.',
  },
  en: {
    back: 'Sessions',
    title: 'Data and privacy',
    languageTitle: 'Interface language',
    languageBody: 'Changes navigation, account, and case-list language for this account.',
    saved: 'Saved',
    saving: 'Saving...',
    failed: 'Could not save language.',
    exportTitle: 'Download my data',
    exportBody: 'Export all data tied to your account (profile, sessions, messages, campaigns, feedback) as one JSON file.',
    exportButton: 'Download JSON',
    deleteTitle: 'Delete account',
    deleteBody: 'Permanently deletes your account and all related data (sessions, messages, campaigns). This cannot be undone.',
    deleteButton: 'Delete account',
    confirmTitle: 'Confirm deletion',
    confirmBody: 'This will permanently delete',
    confirmBodyAfter: 'and all data. Enter your password to confirm.',
    password: 'Password',
    cancel: 'Cancel',
    deleting: 'Deleting...',
    deleteForever: 'Delete forever',
    passwordRequired: 'Enter your password to confirm.',
    wrongPassword: 'Incorrect password.',
    deleteFailed: 'Could not delete account.',
    networkError: 'Connection error. Please try again.',
  },
  es: {
    back: 'Sesiones',
    title: 'Datos y privacidad',
    languageTitle: 'Idioma de interfaz',
    languageBody: 'Cambia el idioma de navegacion, cuenta y lista de casos para esta cuenta.',
    saved: 'Guardado',
    saving: 'Guardando...',
    failed: 'No se pudo guardar el idioma.',
    exportTitle: 'Descargar mis datos',
    exportBody: 'Exporta todos los datos vinculados a tu cuenta (perfil, sesiones, mensajes, campanas, comentarios) en un archivo JSON.',
    exportButton: 'Descargar JSON',
    deleteTitle: 'Eliminar cuenta',
    deleteBody: 'Elimina permanentemente tu cuenta y todos los datos relacionados (sesiones, mensajes, campanas). Esta accion no se puede deshacer.',
    deleteButton: 'Eliminar cuenta',
    confirmTitle: 'Confirmar eliminacion',
    confirmBody: 'Esto eliminara permanentemente',
    confirmBodyAfter: 'y todos los datos. Introduce tu contrasena para confirmar.',
    password: 'Contrasena',
    cancel: 'Cancelar',
    deleting: 'Eliminando...',
    deleteForever: 'Eliminar para siempre',
    passwordRequired: 'Introduce tu contrasena para confirmar.',
    wrongPassword: 'Contrasena incorrecta.',
    deleteFailed: 'No se pudo eliminar la cuenta.',
    networkError: 'Error de conexion. Intentalo de nuevo.',
  },
} satisfies Record<InterfaceLanguage, Record<string, string>>;
