export type Lang = "en" | "uk" | "es";

export const CONTENT = {
  en: {
    nav: {
      exhibits: "Exhibits",
      procedure: "Procedure",
      cases: "Case Files",
    },
    hero: {
      caseNo: "Case Nº 1929 / BRR",
      filed: "Filed: 04 / 20 / 2026",
      kicker: "Browser horror investigations with an AI Case Curator",
      t1: "The Case Curator",
      t2: "is already",
      t3: "listening",
      lede: "Try a single-player horror investigation in text. The free demo gives you up to 10 AI turns or 15 minutes; full beta adds voice and parties of 1–4 investigators.",
      cta: "Try Free Demo",
      ghost: "Read the Dossier",
      proofLabel: "Free demo includes",
      proofs: ["Text only", "1 investigator", "10 AI turns · 15 min"],
    },
    access: {
      open: {
        nav: "Create account →",
        case: "Create account",
        body: "No install. No download. Try the open demo now, or create a free beta account and open a full case.",
        cta: "Create Free Account",
      },
      waitlist: {
        nav: "Join Waitlist →",
        case: "Join waitlist",
        body: "No install. No download. Try the open demo now, or join the queue while the Bureau prepares full access.",
        cta: "Join the Waitlist",
      },
      availability: "The full beta and account registration are available in English and Ukrainian. The demo is also available in Spanish.",
    },
    preview: {
      label: "Live game preview",
      status: "Case Curator online",
      messageMeta: "Case Curator",
      message: "Rain needles the Bureau windows. A sealed archive door waits ahead. No handle. A thin keyhole listens back.",
      objectiveLabel: "Objective",
      objective: "Describe your next move. Inspect, listen, improvise, or risk a d100 check.",
      stats: [
        { k: "Clues", v: "0/3" },
        { k: "Roll", v: "d100" },
        { k: "Mode", v: "Free text" },
      ],
      input: "I inspect the brass hinges...",
    },
    dossier: {
      county: "Arkham County · Records",
      confidential: "Confidential",
      subject: "Subject: The Listener",
      rows: [
        { k: "Classification", v: "Case Curator / Narrator" },
        { k: "Active since", v: "the small hours" },
        { k: "Known aliases", v: "Keeper engine, archive clerk" },
        { k: "Jurisdiction", v: "barrigame.es" },
      ],
      stamp: "Classified",
      stampSub: "Do Not Remove",
    },
    ticker: [
      "Dossier nº 1929 — reopened after ninety-seven years of silence",
      "Witness reports: voices in the static, none of them human",
      "The Case Curator sees every die you roll. Even the ones you hide",
      "Three investigators entered. Two returned. One came back wrong",
      "Evidence recovered from the Elm Street property",
      "Do not read the file after sundown",
    ],
    exhibits: {
      label: "Evidence docket",
      heading: ["What you ", "do", ",\xa0the Case Curator remembers."],
      desc: "Six exhibits from the Bureau logbook. Together they show how Barri turns a browser tab into a persistent horror table.",
      items: [
        {
          num: "I", tag: "Exhibit A",
          title: "The Case Curator never closes the file",
          body: "An AI case handler narrates every scene in real time. It remembers the matchbook in your pocket, the name you gave the barkeep, and the lie you told three sessions ago.",
        },
        {
          num: "II", tag: "Exhibit B",
          title: "The dice do not lie",
          body: "A d100 horror rules engine runs under the hood. Roll against your skills on the virtual table, or call it out and the Case Curator adjudicates on the spot.",
        },
        {
          num: "III", tag: "Exhibit C",
          title: "The record remembers",
          body: "Multi-session campaigns persist between visits. NPCs carry grudges, locations stay changed, and the scars on your investigator follow them into the next case.",
        },
        {
          num: "IV", tag: "Exhibit D",
          title: "Voices from the dark",
          body: "Every character speaks in their own voice. Play the Case Curator's replies aloud whenever you want the investigation to leave the page.",
        },
        {
          num: "V", tag: "Exhibit E",
          title: "No two runs are the same",
          body: "Every session is a new investigation. Different choices, different suspects, different outcomes. The case is the same — the truth is always somewhere else.",
        },
        {
          num: "VI", tag: "Exhibit F",
          title: "Bring your party",
          body: "One to four investigators at the same table. Assign roles — detective, scholar, reporter — and let the AI Case Curator track injuries, sanity, and luck for everyone.",
        },
      ],
    },
    procedure: {
      label: "Procedure log",
      heading: ["How an ", "investigation", " is run."],
      steps: [
        {
          n: "1", tag: "Intake",
          title: "Select a Case File",
          body: "Choose a scenario from the cabinet. Each one is a self-contained investigation with its own ruleset, locations, and suspects.",
        },
        {
          n: "2", tag: "Casting",
          title: "Assemble Your Party",
          body: "Name your investigators, pick their roles, and step into the era. The Case Curator assigns skills, gear, and secrets accordingly.",
        },
        {
          n: "3", tag: "Session",
          title: "Begin the Interview",
          body: "Speak with NPCs, search rooms, follow leads. Voice or text — the Case Curator hears you. Roll dice when she asks, or when your nerve fails you.",
        },
        {
          n: "4", tag: "Archive",
          title: "Close the Case",
          body: "Every session ends with a written summary in the campaign record. Come back for another run — a different approach, a different truth.",
        },
      ],
    },
    cases: {
      label: "Case cabinet",
      heading: ["Open ", "case files."],
      desc: "One demo file is open now. Additional cases are staged in the cabinet and unlock for registered investigators.",
      files: [
        {
          id: "File № 01 · d100 Horror", badge: "Open", badgeSealed: false,
          cls: "case-1",
          title: "The Haunting",
          sub: "A draughty house on Elm Street.",
          meta: [
            { k: "Sessions", v: "1" }, { k: "Players", v: "1 – 4" },
            { k: "Tone", v: "Classic horror" }, { k: "Duration", v: "≈ 3 h" },
          ],
          brief: "A family hires you to certify the Corbitt house on Elm Street as fit for purchase. The previous tenants left in a hurry. Their belongings are still inside. Something in the cellar has been collecting them — and waiting. Every run reveals new angles: follow the priest's trail, dig into the cult's history, or risk the ritual room alone. The ending depends entirely on what you choose to believe.",
          replayable: "Fully replayable · outcome changes with every approach",
          cta: "Open the file",
          stamp: null,
        },
        {
          id: "File № 02 · d100 Horror · Campaign", badge: "Multi-Session", badgeSealed: true,
          cls: "case-2",
          title: "The Last Telegram",
          sub: "Four locations. One message from the dead.",
          meta: [
            { k: "Sessions", v: "3 – 5" }, { k: "Players", v: "2 – 4" },
            { k: "Tone", v: "Investigative" }, { k: "Duration", v: "≈ 12 h" },
          ],
          brief: "At 22:14 a telegram arrives at the Arkham bureau. The sender's name is on a headstone six miles east — interred eleven days prior. The wire contains three words and a grid reference. A multi-session investigation across four locations: follow the signals to find out who sent it, why they died, and whether the answer is worse than not knowing. Each run chooses different witnesses to trust — and pays a different price.",
          replayable: "Campaign · multiple paths to the truth",
          cta: "Open the file",
          stamp: "Campaign",
        },
        {
          id: "File № — · In Preparation", badge: "Sealed", badgeSealed: true,
          cls: "case-3",
          title: "The Red Vestments",
          sub: "Evidence gathered. Cataloguing ongoing.",
          meta: [
            { k: "Sessions", v: "—" }, { k: "Players", v: "—" },
            { k: "Tone", v: "Occult" }, { k: "Duration", v: "—" },
          ],
          brief: "A cathedral empties between matins and sundown. No bodies. No blood. Only a single red thread across every pew. Three confessionals sealed from the inside. The sacristan cannot be reached. The Bureau is not yet accepting investigators on this case.",
          replayable: "Coming soon · clearance pending",
          cta: null,
          stamp: "Coming Soon",
        },
      ],
    },
    cta: {
      label: "Final notice",
      h1: "The file is open.",
      h2: "Will you read it?",
    },
    footer: {
      credit1: "© 1929 – 2026 · Barri Bureau of Unspeakable Affairs",
      credit2: "No known investigators were harmed in the filing of this dossier.",
      disclaimer: "An independent, original work of interactive horror fiction. Not affiliated with any tabletop RPG publisher.",
    },
  },

  /* ============================================================ */
  uk: {
    nav: {
      exhibits: "Докази",
      procedure: "Процедура",
      cases: "Справи",
    },
    hero: {
      caseNo: "Справа №1929 / ЗГ",
      filed: "Подано: 20 / 04 / 2026",
      kicker: "Браузерні horror-розслідування з AI-Куратором справи",
      t1: "Куратор справи",
      t2: "вже",
      t3: "слухає",
      lede: "Спробуйте одиночне horror-розслідування текстом. Безкоштовне демо дає до 10 ходів AI або 15 хвилин; повна бета додає голос і групи від 1 до 4 слідчих.",
      cta: "Спробувати демо",
      ghost: "Прочитати досьє",
      proofLabel: "У безкоштовному демо",
      proofs: ["Лише текст", "1 слідчий", "10 ходів AI · 15 хв"],
    },
    access: {
      open: {
        nav: "Створити акаунт →",
        case: "Створити акаунт",
        body: "Жодного встановлення чи завантаження. Спробуйте відкрите демо або створіть безкоштовний бета-акаунт і відкрийте повну справу.",
        cta: "Створити акаунт",
      },
      waitlist: {
        nav: "Стати в чергу →",
        case: "Стати в чергу",
        body: "Жодного встановлення чи завантаження. Спробуйте відкрите демо або станьте в чергу, поки Бюро готує повний доступ.",
        cta: "Стати в чергу",
      },
      availability: "Повна бета й реєстрація доступні англійською та українською. Демо також доступне іспанською.",
    },
    preview: {
      label: "Прев'ю гри",
      status: "Куратор справи онлайн",
      messageMeta: "Куратор справи",
      message: "Дощ б'є по вікнах Бюро. Попереду запечатані архівні двері. Без ручки. Тонка шпарина слухає у відповідь.",
      objectiveLabel: "Ціль",
      objective: "Опишіть наступну дію. Оглядайте, слухайте, імпровізуйте або ризикуйте перевіркою d100.",
      stats: [
        { k: "Зачіпки", v: "0/3" },
        { k: "Кидок", v: "d100" },
        { k: "Режим", v: "Вільний текст" },
      ],
      input: "Я оглядаю латунні петлі...",
    },
    dossier: {
      county: "Аркхем · Архів справ",
      confidential: "Таємно",
      subject: "Суб'єкт: Слухач",
      rows: [
        { k: "Класифікація", v: "Куратор справи / Розповідач" },
        { k: "Активний з", v: "глибокої ночі" },
        { k: "Псевдоніми", v: "Рушій Куратора, архівний писар" },
        { k: "Юрисдикція", v: "barrigame.es" },
      ],
      stamp: "Таємно",
      stampSub: "Не виносити",
    },
    ticker: [
      "Досьє №1929 — відкрите після дев'яноста семи років тиші",
      "Показання свідків: голоси в ефірі — жодного людського",
      "Куратор справи бачить кожен ваш кидок кубика. Навіть приховані",
      "Три слідчі увійшли. Двоє повернулись. Третій — вже не той",
      "Речові докази вилучено з будинку на вулиці Елм",
      "Не читайте справу після заходу сонця",
    ],
    exhibits: {
      label: "Реєстр доказів",
      heading: ["Що ви ", "робите", ",\xa0Куратор справи пам'ятає."],
      desc: "Шість записів із реєстру Бюро. Разом вони показують, як Barri перетворює вкладку браузера на живий horror-стіл.",
      items: [
        {
          num: "I", tag: "Доказ А",
          title: "Куратор справи не закриває файл",
          body: "AI-куратор веде розповідь у реальному часі. Він пам'ятає сірники у вашій кишені, ім'я, яке ви дали бармену, і брехню, сказану три сесії тому.",
        },
        {
          num: "II", tag: "Доказ Б",
          title: "Кубики не брешуть",
          body: "Під капотом працює d100-рушій для горор-розслідувань. Кидайте проти своїх навичок на віртуальному столі — Куратор справи розсудить на місці.",
        },
        {
          num: "III", tag: "Доказ В",
          title: "Архів пам'ятає",
          body: "Багатосесійні кампанії зберігаються між відвідуваннями. Персонажі тримають образи, локації залишаються зміненими, а шрами слідчого переходять у наступну справу.",
        },
        {
          num: "IV", tag: "Доказ Г",
          title: "Голоси з темряви",
          body: "Кожен персонаж говорить власним голосом. Вмикайте озвучення відповідей Куратора, коли хочете, щоб розслідування вийшло за межі сторінки.",
        },
        {
          num: "V", tag: "Доказ Д",
          title: "Кожне проходження інше",
          body: "Кожна сесія — нове розслідування. Різні вибори, різні підозрювані, різні кінці. Справа та сама — правда щоразу деінде.",
        },
        {
          num: "VI", tag: "Доказ Е",
          title: "Беріть команду",
          body: "Від одного до чотирьох слідчих за одним столом. Обирайте ролі — детектив, вчений, журналіст — Куратор справи веде стан, здоров'я та удачу для кожного.",
        },
      ],
    },
    procedure: {
      label: "Протокол процедури",
      heading: ["Як проводиться ", "розслідування", "."],
      steps: [
        {
          n: "1", tag: "Реєстрація",
          title: "Обрати справу",
          body: "Виберіть сценарій із шухляди. Кожен — самостійне розслідування з власними правилами, локаціями та підозрюваними.",
        },
        {
          n: "2", tag: "Склад",
          title: "Зібрати команду",
          body: "Назвіть слідчих, оберіть їхні ролі та зануртесь в епоху. Куратор справи розподілить навички, спорядження та таємниці.",
        },
        {
          n: "3", tag: "Сесія",
          title: "Почати допит",
          body: "Розмовляйте з персонажами, обшукуйте кімнати, ідіть за слідами. Голос або текст — Куратор справи чує. Кидайте кубики коли він просить або коли нерви здають.",
        },
        {
          n: "4", tag: "Архів",
          title: "Закрити справу",
          body: "Кожна сесія завершується письмовим підсумком у записах кампанії. Повертайтесь на нове проходження — інший підхід, інша правда.",
        },
      ],
    },
    cases: {
      label: "Шухляда справ",
      heading: ["Відкриті ", "справи."],
      desc: "Одна демо-справа відкрита вже зараз. Інші справи стоять у шухляді й відкриються для зареєстрованих слідчих.",
      files: [
        {
          id: "Справа № 01 · d100 горор", badge: "Відкрита", badgeSealed: false,
          cls: "case-1",
          title: "Примарний будинок",
          sub: "Будинок із протягом на вулиці Елм.",
          meta: [
            { k: "Сесії", v: "1" }, { k: "Гравці", v: "1 – 4" },
            { k: "Тон", v: "Класичний жах" }, { k: "Тривалість", v: "≈ 3 год" },
          ],
          brief: "Родина Армітедж наймає вас, щоб перевірити будинок Корбіта на вулиці Елм перед покупкою. Попередні мешканці пішли поспіхом — їхні речі досі там. Щось у підвалі їх збирало. І чекало. Щоразу — новий маршрут: слідуйте за слідом священника, розкопайте історію культу або ризикуйте обрядовою кімнатою на самоті. Кінець залежить від того, чому ви вирішили вірити.",
          replayable: "Можна проходити знову · фінал змінюється щоразу",
          cta: "Відкрити справу",
          stamp: null,
        },
        {
          id: "Справа № 02 · d100 горор · Кампанія", badge: "Декілька сесій", badgeSealed: true,
          cls: "case-2",
          title: "Остання телеграма",
          sub: "Чотири локації. Одне повідомлення від мертвого.",
          meta: [
            { k: "Сесії", v: "3 – 5" }, { k: "Гравці", v: "2 – 4" },
            { k: "Тон", v: "Розслідування" }, { k: "Тривалість", v: "≈ 12 год" },
          ],
          brief: "О 22:14 до аркхемського бюро надходить телеграма. Ім'я відправника на надгробку за шість миль — похований одинадцять днів тому. У повідомленні три слова й координати. Розслідування через чотири локації: хто надіслав, як загинув і чи є відповідь гіршою за незнання. Кожне проходження обирає інших свідків — і платить іншу ціну.",
          replayable: "Кампанія · кілька шляхів до правди",
          cta: "Відкрити справу",
          stamp: "Кампанія",
        },
        {
          id: "Справа № — · В підготовці", badge: "Засекречено", badgeSealed: true,
          cls: "case-3",
          title: "Червоні ризи",
          sub: "Докази зібрано. Каталогізація триває.",
          meta: [
            { k: "Сесії", v: "—" }, { k: "Гравці", v: "—" },
            { k: "Тон", v: "Окультне" }, { k: "Тривалість", v: "—" },
          ],
          brief: "Собор спорожнів між заутренею та заходом сонця. Ні тіл. Ні крові. Лише червона нитка на кожній лаві. Три сповідальні заблоковані зсередини. Паламар недосяжний. Бюро поки не приймає слідчих у цю справу.",
          replayable: "Незабаром · дозвіл очікується",
          cta: null,
          stamp: "Скоро",
        },
      ],
    },
    cta: {
      label: "Фінальне повідомлення",
      h1: "Справа відкрита.",
      h2: "Ви готові читати?",
    },
    footer: {
      credit1: "© 1929 – 2026 · Barri — Бюро невимовних справ",
      credit2: "Жоден слідчий офіційно не постраждав під час складання цього досьє.",
      disclaimer: "Незалежний оригінальний твір інтерактивного жаху. Не пов'язаний із жодним видавцем настільних рольових ігор.",
    },
  },

  /* ============================================================ */
  es: {
    nav: {
      exhibits: "Pruebas",
      procedure: "Procedimiento",
      cases: "Expedientes",
    },
    hero: {
      caseNo: "Expediente Nº 1929 / BRR",
      filed: "Fechado: 20 / 04 / 2026",
      kicker: "Investigaciones de terror en navegador con un Curador de IA",
      t1: "El Curador del caso",
      t2: "ya está",
      t3: "escuchando",
      lede: "Prueba una investigación de terror para un solo jugador y por texto. La demo ofrece hasta 10 turnos de IA o 15 minutos; la beta completa añade voz y grupos de 1–4 investigadores.",
      cta: "Probar demo gratis",
      ghost: "Leer el dosier",
      proofLabel: "La demo gratis incluye",
      proofs: ["Solo texto", "1 investigador", "10 turnos IA · 15 min"],
    },
    access: {
      open: {
        nav: "Crear cuenta · EN/UK →",
        case: "Crear cuenta · EN/UK",
        body: "Sin instalación ni descarga. Prueba la demo en español o crea una cuenta beta gratuita para abrir un caso completo en inglés o ucraniano.",
        cta: "Crear cuenta · EN/UK",
      },
      waitlist: {
        nav: "Unirse a la lista →",
        case: "Unirse a la lista",
        body: "Sin instalación ni descarga. Prueba la demo en español o únete a la lista mientras el Buró prepara el acceso completo.",
        cta: "Unirse a la lista",
      },
      availability: "La beta completa y el registro están disponibles en inglés y ucraniano. La demo también está disponible en español.",
    },
    preview: {
      label: "Vista de partida",
      status: "Curador online",
      messageMeta: "Curador",
      message: "La lluvia golpea las ventanas del Buró. Una puerta de archivo sellada espera delante. Sin pomo. Una cerradura fina escucha.",
      objectiveLabel: "Objetivo",
      objective: "Describe tu siguiente movimiento. Inspecciona, escucha, improvisa o arriesga una tirada d100.",
      stats: [
        { k: "Pistas", v: "0/3" },
        { k: "Tirada", v: "d100" },
        { k: "Modo", v: "Texto libre" },
      ],
      input: "Examino las bisagras de latón...",
    },
    dossier: {
      county: "Condado de Arkham · Archivos",
      confidential: "Confidencial",
      subject: "Sujeto: El Oyente",
      rows: [
        { k: "Clasificación", v: "Curador del caso / Narrador" },
        { k: "Activo desde", v: "las horas pequeñas" },
        { k: "Alias conocidos", v: "Motor del Curador, archivero" },
        { k: "Jurisdicción", v: "barrigame.es" },
      ],
      stamp: "Clasificado",
      stampSub: "No retirar",
    },
    ticker: [
      "Expediente nº 1929 — reabierto tras noventa y siete años de silencio",
      "Declaraciones de testigos: voces en la estática, ninguna humana",
      "El Curador del caso ve cada dado que tiras. Incluso los que escondes",
      "Tres investigadores entraron. Dos regresaron. El tercero volvió cambiado",
      "Pruebas recuperadas de la propiedad en Elm Street",
      "No leas el expediente después del atardecer",
    ],
    exhibits: {
      label: "Registro de pruebas",
      heading: ["Lo que ", "haces", ",\xa0el Curador lo recuerda."],
      desc: "Seis pruebas del registro del Buró. Juntas muestran cómo Barri convierte una pestaña del navegador en una mesa de terror persistente.",
      items: [
        {
          num: "I", tag: "Prueba A",
          title: "El Curador nunca cierra el expediente",
          body: "Un curador de caso IA narra cada escena en tiempo real. Recuerda las cerillas en tu bolsillo, el nombre que le diste al barman y la mentira que contaste hace tres sesiones.",
        },
        {
          num: "II", tag: "Prueba B",
          title: "Los dados no mienten",
          body: "Un motor d100 para terror investigativo funciona bajo el capó. Tira contra tus habilidades en la mesa virtual — el Curador juzgará en el acto.",
        },
        {
          num: "III", tag: "Prueba C",
          title: "El registro recuerda",
          body: "Las campañas de varias sesiones persisten entre visitas. Los PNJ guardan rencores, las ubicaciones permanecen alteradas y las cicatrices de tu investigador le siguen al siguiente caso.",
        },
        {
          num: "IV", tag: "Prueba D",
          title: "Voces desde la oscuridad",
          body: "Cada personaje habla con su propia voz. Reproduce las respuestas del Curador cuando quieras que la investigación salga de la página.",
        },
        {
          num: "V", tag: "Prueba E",
          title: "Nunca hay dos partidas iguales",
          body: "Cada sesión es una investigación nueva. Diferentes elecciones, diferentes sospechosos, diferentes desenlaces. El caso es el mismo — la verdad siempre está en otro lugar.",
        },
        {
          num: "VI", tag: "Prueba F",
          title: "Trae tu grupo",
          body: "De uno a cuatro investigadores en la misma mesa. Elige roles — detective, erudito, periodista — y deja que el Curador lleve el control de lesiones, cordura y suerte.",
        },
      ],
    },
    procedure: {
      label: "Protocolo",
      heading: ["Cómo se conduce ", "una investigación", "."],
      steps: [
        {
          n: "1", tag: "Admisión",
          title: "Seleccionar expediente",
          body: "Elige un escenario del archivo. Cada uno es una investigación independiente con su propio reglamento, ubicaciones y sospechosos.",
        },
        {
          n: "2", tag: "Reparto",
          title: "Reunir al grupo",
          body: "Nombra a tus investigadores, elige sus roles y sumérgete en la época. El Curador del caso distribuirá habilidades, equipamiento y secretos.",
        },
        {
          n: "3", tag: "Sesión",
          title: "Comenzar la investigación",
          body: "Habla con los PNJ, registra habitaciones, sigue pistas. Voz o texto — el Curador te escucha. Tira los dados cuando lo pida, o cuando los nervios te fallen.",
        },
        {
          n: "4", tag: "Archivo",
          title: "Cerrar el caso",
          body: "Cada sesión termina con un resumen escrito en el registro de campaña. Vuelve para otra partida — un enfoque diferente, una verdad diferente.",
        },
      ],
    },
    cases: {
      label: "Archivo de casos",
      heading: ["Expedientes ", "abiertos."],
      desc: "Un expediente demo está abierto ahora. Los demás casos esperan en el archivo y se desbloquean para investigadores registrados.",
      files: [
        {
          id: "Expediente № 01 · d100 terror", badge: "Abierto", badgeSealed: false,
          cls: "case-1",
          title: "La casa encantada",
          sub: "Una casa fría en Elm Street.",
          meta: [
            { k: "Sesiones", v: "1" }, { k: "Jugadores", v: "1 – 4" },
            { k: "Tono", v: "Terror clásico" }, { k: "Duración", v: "≈ 3 h" },
          ],
          brief: "La familia Armitage te contrata para certificar la casa Corbitt en Elm Street antes de comprarla. Los inquilinos anteriores se fueron a toda prisa — sus pertenencias siguen dentro. Algo en el sótano las ha estado coleccionando. Y esperando. Cada partida ofrece nuevas rutas: sigue el rastro del sacerdote, investiga la historia del culto o arriesga la sala del ritual en solitario. El final depende de lo que decidas creer.",
          replayable: "Totalmente rejugable · el desenlace cambia con cada enfoque",
          cta: "Abrir expediente",
          stamp: null,
        },
        {
          id: "Expediente № 02 · d100 terror · Campaña", badge: "Multi-sesión", badgeSealed: true,
          cls: "case-2",
          title: "El último telegrama",
          sub: "Cuatro ubicaciones. Un mensaje del más allá.",
          meta: [
            { k: "Sesiones", v: "3 – 5" }, { k: "Jugadores", v: "2 – 4" },
            { k: "Tono", v: "Investigativo" }, { k: "Duración", v: "≈ 12 h" },
          ],
          brief: "A las 22:14 llega un telegrama a la oficina de Arkham. El nombre del remitente está en una lápida a diez kilómetros — enterrado hace once días. El mensaje contiene tres palabras y una referencia de cuadrícula. Una investigación de varias sesiones a través de cuatro ubicaciones: sigue las señales para descubrir quién lo envió, por qué murió y si la respuesta es peor que la ignorancia. Cada partida elige distintos testigos — y paga un precio diferente.",
          replayable: "Campaña · múltiples caminos hacia la verdad",
          cta: "Abrir expediente",
          stamp: "Campaña",
        },
        {
          id: "Expediente № — · En preparación", badge: "Sellado", badgeSealed: true,
          cls: "case-3",
          title: "Las vestiduras rojas",
          sub: "Pruebas reunidas. Catalogación en curso.",
          meta: [
            { k: "Sesiones", v: "—" }, { k: "Jugadores", v: "—" },
            { k: "Tono", v: "Ocultismo" }, { k: "Duración", v: "—" },
          ],
          brief: "Una catedral se vacía entre maitines y el ocaso. Sin cuerpos. Sin sangre. Solo un hilo rojo en cada banco. Tres confesionarios sellados desde dentro. El sacristán no puede ser localizado. El Buró aún no acepta investigadores para este caso.",
          replayable: "Próximamente · autorización pendiente",
          cta: null,
          stamp: "Próximamente",
        },
      ],
    },
    cta: {
      label: "Aviso final",
      h1: "El expediente está abierto.",
      h2: "¿Lo leerás?",
    },
    footer: {
      credit1: "© 1929 – 2026 · Barri — Buró de Asuntos Indecibles",
      credit2: "Ningún investigador conocido resultó herido durante la elaboración de este expediente.",
      disclaimer: "Obra original e independiente de ficción interactiva de terror. No afiliada a ninguna editorial de juegos de rol.",
    },
  },
} as const;
